import { describe, it, expect } from "vitest";
import { generateDtoContent } from "../commands/makeDto";
import type { TModelMeta, TMigrationMeta } from "../parser";

// ─── make:dto content generation ────────────────────────────────────────────

const makeModel = (overrides: Partial<TModelMeta> = {}): TModelMeta => ({
  className: "User",
  attrsType: "TUserAttrs",
  table: "users",
  primaryKey: "id",
  timestamps: true,
  softDeletes: false,
  relations: [],
  casts: {},
  scopes: [],
  hooks: [],
  fields: [
    { name: "id", tsType: "string", optional: false },
    { name: "name", tsType: "string", optional: false },
    { name: "email", tsType: "string", optional: false },
    { name: "created_at", tsType: "string", optional: false },
    { name: "updated_at", tsType: "string", optional: false },
  ],
  ...overrides,
});

const makeMigration = (overrides: Partial<TMigrationMeta> = {}): TMigrationMeta => ({
  name: "20260329_create_users",
  table: "users",
  columns: [
    { name: "id", type: "TEXT", nullable: false, primary: true, hasDefault: false },
    { name: "name", type: "TEXT", nullable: false, primary: false, hasDefault: false },
    { name: "email", type: "TEXT", nullable: false, primary: false, hasDefault: false },
    { name: "created_at", type: "TEXT", nullable: false, primary: false, hasDefault: false },
    { name: "updated_at", type: "TEXT", nullable: false, primary: false, hasDefault: false },
  ],
  hasTimestamps: true,
  hasSoftDeletes: false,
  foreignKeys: [],
  ...overrides,
});

describe("generateDtoContent", () => {
  it("generates TModelAttrs from model fields", () => {
    const content = generateDtoContent(makeModel(), null);
    expect(content).toContain("export type TUserAttrs");
    expect(content).toContain("id: string;");
    expect(content).toContain("name: string;");
    expect(content).toContain("email: string;");
  });

  it("generates TModelCreateAttrs omitting auto fields", () => {
    const content = generateDtoContent(makeModel(), null);
    expect(content).toContain("export type TUserCreateAttrs");
    // Should NOT have id, created_at, updated_at
    const createBlock = content.split("TUserCreateAttrs")[1];
    expect(createBlock).not.toContain("id:");
    expect(createBlock).not.toContain("created_at:");
    expect(createBlock).not.toContain("updated_at:");
    // Should have name and email
    expect(createBlock).toContain("name:");
    expect(createBlock).toContain("email:");
  });

  it("handles optional fields", () => {
    const model = makeModel({
      fields: [
        { name: "id", tsType: "string", optional: false },
        { name: "bio", tsType: "string | null", optional: true },
      ],
    });
    const content = generateDtoContent(model, null);
    expect(content).toContain("bio?: string | null;");
  });

  it("falls back to migration columns when model has no fields", () => {
    const model = makeModel({ fields: [] });
    const migration = makeMigration();
    const content = generateDtoContent(model, migration);
    expect(content).toContain("export type TUserAttrs");
    expect(content).toContain("id: string;");
    expect(content).toContain("name: string;");
  });

  it("includes auto-generated header comment", () => {
    const content = generateDtoContent(makeModel(), null);
    expect(content).toContain("Auto-generated by d1-eloquent make:dto");
    expect(content).toContain("Source model: User");
  });

  it("omits deleted_at from create attrs", () => {
    const model = makeModel({
      softDeletes: true,
      fields: [
        { name: "id", tsType: "string", optional: false },
        { name: "name", tsType: "string", optional: false },
        { name: "deleted_at", tsType: "string | null", optional: true },
        { name: "created_at", tsType: "string", optional: false },
        { name: "updated_at", tsType: "string", optional: false },
      ],
    });
    const content = generateDtoContent(model, null);
    const createBlock = content.split("TUserCreateAttrs")[1];
    expect(createBlock).not.toContain("deleted_at");
  });
});
