import { writeFile } from "node:fs/promises";
import { register } from "../registry";
import { parseModelFile, parseMigrationFile, sqliteTypeToTs, type TModelMeta, type TMigrationMeta } from "../parser";
import { collectModelFiles, collectMigrationFiles, ensureDir, resolveOutputDir, confirmOverwrite } from "../utils";
import type { TCommand } from "../types";

const AUTO_FIELDS = new Set(["id", "created_at", "updated_at", "deleted_at"]);

const findModelFile = async (name: string): Promise<string | null> => {
  const files = await collectModelFiles();
  const lower = name.toLowerCase();
  return files.find((f) => {
    const filename = f.split("/").pop()?.replace(/\.ts$/, "").toLowerCase();
    return filename === lower;
  }) ?? null;
};

const findMigrationForTable = async (table: string): Promise<TMigrationMeta | null> => {
  const files = await collectMigrationFiles();
  for (const file of files) {
    const meta = await parseMigrationFile(file);
    if (meta?.table === table) return meta;
  }
  return null;
};

/** Generate DTO content from model + migration metadata. */
export const generateDtoContent = (model: TModelMeta, migration: TMigrationMeta | null): string => {
  const lines: string[] = [];
  const className = model.className;

  lines.push(`// Auto-generated by d1-eloquent make:dto`);
  lines.push(`// Source model: ${className}`);
  lines.push(``);

  // Use type fields from model if available, fall back to migration columns
  if (model.fields.length > 0) {
    // Full attributes type (all fields)
    lines.push(`export type T${className}Attrs = {`);
    for (const f of model.fields) {
      lines.push(`  ${f.name}${f.optional ? "?" : ""}: ${f.tsType};`);
    }
    lines.push(`};`);
    lines.push(``);

    // Create attributes type (omit auto-generated fields)
    const createFields = model.fields.filter((f) => !AUTO_FIELDS.has(f.name));
    if (createFields.length > 0) {
      lines.push(`export type T${className}CreateAttrs = {`);
      for (const f of createFields) {
        lines.push(`  ${f.name}${f.optional ? "?" : ""}: ${f.tsType};`);
      }
      lines.push(`};`);
      lines.push(``);
    }
  } else if (migration) {
    // Fall back to migration columns → derive TS types
    lines.push(`export type T${className}Attrs = {`);
    for (const col of migration.columns) {
      const tsType = sqliteTypeToTs(col);
      const nullable = col.nullable && !col.primary;
      lines.push(`  ${col.name}${nullable ? "?" : ""}: ${tsType}${nullable ? " | null" : ""};`);
    }
    lines.push(`};`);
    lines.push(``);

    const createCols = migration.columns.filter((c) => !AUTO_FIELDS.has(c.name));
    if (createCols.length > 0) {
      lines.push(`export type T${className}CreateAttrs = {`);
      for (const col of createCols) {
        const tsType = sqliteTypeToTs(col);
        const nullable = col.nullable;
        lines.push(`  ${col.name}${nullable ? "?" : ""}: ${tsType}${nullable ? " | null" : ""};`);
      }
      lines.push(`};`);
      lines.push(``);
    }
  }

  return lines.join("\n");
};

/** Core logic — callable by make:types. Returns the output path or null if skipped. */
export const makeDtoRun = async (
  modelName: string,
  outDir: string,
  force: boolean,
): Promise<string | null> => {
  const file = await findModelFile(modelName);
  if (!file) {
    console.error(`Model file not found: ${modelName}`);
    return null;
  }

  const model = await parseModelFile(file);
  if (!model) {
    console.error(`Could not parse model from: ${file}`);
    return null;
  }

  const migration = model.table ? await findMigrationForTable(model.table) : null;
  const content = generateDtoContent(model, migration);

  if (!content.includes("export type")) {
    console.warn(`No fields found for ${modelName} — skipping`);
    return null;
  }

  await ensureDir(outDir);
  const outPath = `${outDir}/${model.className}Attrs.ts`;

  if (!(await confirmOverwrite(outPath, force))) {
    console.log(`Skipped: ${outPath}`);
    return null;
  }

  await writeFile(outPath, content, "utf-8");
  console.log(`Created DTO: ${outPath}`);
  return outPath;
};

const command: TCommand = {
  meta: {
    name: "make:dto",
    description: "Generate typed attributes interface for a model",
    usage: "make:dto <model> [--out-dir=path] [--force]",
    category: "generate",
  },
  async run(ctx) {
    const name = ctx.args[0];
    if (!name) {
      console.error("Usage: make:dto <model>  (e.g. make:dto User)");
      process.exit(1);
    }

    const outDir = resolveOutputDir(ctx.flags.get("out-dir"), "src/types/generated");
    const force = ctx.flags.bool("force");

    await makeDtoRun(name, outDir, force);
  },
};

register(command);
export { command as makeDto };
