import { writeFile } from "node:fs/promises";
import { register } from "../registry";
import { parseModelFile } from "../parser";
import { collectModelFiles, ensureDir, resolveOutputDir, confirmOverwrite } from "../utils";
import { makeDtoRun } from "./makeDto";
import type { TCommand } from "../types";

type TTypesResult = {
  generated: string[];
  skipped: string[];
  errors: string[];
};

const command: TCommand = {
  meta: {
    name: "make:types",
    description: "Generate typed attributes for all models + barrel index",
    usage: "make:types [--out-dir=path] [--force] [--json]",
    category: "generate",
  },
  async run(ctx) {
    const outDir = resolveOutputDir(ctx.flags.get("out-dir"), "src/types/generated");
    const force = ctx.flags.bool("force");
    const jsonOutput = ctx.flags.bool("json");

    const modelFiles = await collectModelFiles();

    if (modelFiles.length === 0) {
      if (jsonOutput) {
        console.log(JSON.stringify({ generated: [], skipped: [], errors: [] }, null, 2));
      } else {
        console.log("No model files found.");
      }
      return;
    }

    const result: TTypesResult = { generated: [], skipped: [], errors: [] };

    if (!jsonOutput) {
      console.log(`\nGenerating types for ${modelFiles.length} model(s)...\n`);
    }

    for (const file of modelFiles) {
      let model;
      try {
        model = await parseModelFile(file);
      } catch {
        const name = file.split("/").pop() ?? file;
        if (!jsonOutput) console.warn(`  Skipping unparseable: ${name}`);
        result.errors.push(file);
        continue;
      }

      if (!model) {
        result.skipped.push(file);
        continue;
      }

      const outPath = await makeDtoRun(model.className, outDir, force);
      if (outPath) {
        result.generated.push(outPath);
      } else {
        result.skipped.push(file);
      }
    }

    // Generate barrel index
    if (result.generated.length > 0) {
      await ensureDir(outDir);
      const indexPath = `${outDir}/index.ts`;

      const exports = result.generated
        .map((p) => {
          const filename = p.split("/").pop()!.replace(/\.ts$/, "");
          return `export * from "./${filename}";`;
        })
        .sort()
        .join("\n");

      const indexContent = `// Auto-generated by d1-eloquent make:types\n${exports}\n`;

      if (await confirmOverwrite(indexPath, force)) {
        await writeFile(indexPath, indexContent, "utf-8");
        if (!jsonOutput) console.log(`Created barrel: ${indexPath}`);
      }
    }

    if (jsonOutput) {
      console.log(JSON.stringify(result, null, 2));
    } else {
      console.log(`\nDone: ${result.generated.length} generated, ${result.skipped.length} skipped${result.errors.length ? `, ${result.errors.length} errors` : ""}\n`);
    }
  },
};

register(command);
export { command as makeTypes };
